using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine;

namespace BuildABot
{
    
    /**
     * The base representation and data of all character attacks.
     */
    public abstract class AttackData : ScriptableObject
    {
        
        [Tooltip("The effects associated with this attack.")]
        [SerializeField] protected List<EffectInstance> effects;
        
        [Header("Offset")]
        
        [Tooltip("The offset to apply between the character and the start point of the attack.")]
        [SerializeField] protected Vector2 offset;

        [Tooltip("The offset of the attack along the X axis over time.")]
        [SerializeField] protected AnimationCurve offsetXCurve = AnimationCurve.Constant(0, 1, 1);
        
        [Tooltip("The offset of the attack along the Y axis over time.")]
        [SerializeField] protected AnimationCurve offsetYCurve = AnimationCurve.Constant(0, 1, 1);

        [Tooltip("Should the offset be multiplied by the character's look direction?")]
        [SerializeField] protected bool offsetInLookDirection = true;
        
        [Header("Size")]
        
        [Tooltip("Is the size of this attack relative to the bounds of the attacking character?")]
        [SerializeField] protected bool useRelativeSize = true;
        
        [Tooltip("The size of the attack area.")]
        [SerializeField] protected Vector2 size = Vector2.one;
        
        [Header("Flags")]

        [Tooltip("Can this attack hit the attacker who triggered it?")]
        [SerializeField] protected bool canHitSelf;

        [Tooltip("Can this attack hit the same target multiple times?")]
        [SerializeField] protected bool allowMultiHit;
        
        [Tooltip("Is movement of the character allowed while performing this attack?")]
        [SerializeField] protected bool allowMovement = true;
        
        [Tooltip("Can this attack be interrupted?")]
        [SerializeField] protected bool canInterrupt = true;

        /**
         * Performs this attack for the provided attacker. This will return a list of the hit enemies.
         * <param name="instigator">The combat controller that is performing this attack.</param>
         * <param name="hits">The characters that were hit by this attack. Do not access until finished.</param>
         * <param name="onProgress">An optional function to call as the attack progresses.</param>
         * <param name="onComplete"> An action performed after execution finishes. </param>
         * <returns>The coroutine IEnumerator generated by the action used to cancel the attack if needed.</returns>
         */
        public abstract IEnumerator Execute(CombatController instigator, List<Character> hits, Action<float> onProgress = null, Action onComplete = null);

        /**
         * Handles cancelling this attack.
         * <param name="instigator">The combat controller that is performing this attack.</param>
         * <param name="coroutine">The coroutine tracked by the controller.</param>
         * <returns>True if the attack could be cancelled.</returns>
         */
        public virtual bool TryCancel(CombatController instigator, IEnumerator coroutine)
        {
            if (!canInterrupt) return false;
            if (null != coroutine)
            {
                instigator.StopCoroutine(coroutine);
            }
            if (!allowMovement) instigator.Character.CharacterMovement.CanMove = true;
            return true;
        }

    }
}